# Numpy Revision

In [23]:
import numpy as np

In [24]:
a = np.array([1, 2, 3])             # 1D array
b = np.array([[1, 2], [3, 4]])      # 2D array
print(a.shape)  # (3,)
print(b.shape)  # (2, 2)
print(a.dtype) # int32
print(b.dtype) # int32

(3,)
(2, 2)
int32
int32


Indexing and Slicing

In [25]:
print(b[0, 1]) # first row, second column
print(b[:, 1]) # all rows, second column
print(b[1]) # second row

2
[2 4]
[3 4]


Basic Operations

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)  # Element-wise addition
print(x * y)  # Element-wise multiplication
print (x ** 2)  # Element-wise square
print(np.dot(x, y))  # Dot product
print(np.sum(x))  # Sum of elements
print(np.mean(x))  # Mean of elements
print(np.max(x))  # Maximum element
print(np.min(x))  # Minimum element
print(np.sqrt(x))  # Element-wise square root
print(np.exp(x))  # Element-wise exponential
print(np.log(x))  # Element-wise natural logarithm
print(np.sin(x))  # Element-wise sine
print(np.arange(0, 10, 2))  # Create an array with values from 0 to 10 with a step of 2
print(np.linspace(0, 1, 5))  # Create an array with 5 values evenly spaced between 0 and 1
print(np.eye(3))  # Create a 3x3 identity matrix
print(np.zeros((2, 2)))  # Create a 2x2 array filled with zeros
print(np.ones((2, 2)))  # Create a 2x2 array filled with ones  

[5 7 9]
[ 4 10 18]
[1 4 9]
32
6
2.0
3
1
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


Broadcasting (same rules as PyTorch)

In [27]:
x = np.array([[1], [2], [3]])
y = np.array([10, 20])
print(x + y)  # Broadcasting: adds y to each row of x
print((x + y).shape)
print((x + y).dtype)  # Check the dtype after broadcasting

[[11 21]
 [12 22]
 [13 23]]
(3, 2)
int32


Reshaping, Transposing

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
print(a.T) # shape (3, 2)

# Think of reshaping as flattening the array and then rearranging it
b = a.reshape(3, 2)  # Reshape to (3, 2)
print(b) 

c = a.flatten()  # Flatten the array to 1D
print(c)  # shape (6,)

[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Aggregations

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(a))           # sum of all elements
print(np.sum(a, axis=0))   # [5 7 9] sum across rows
print(np.sum(a, axis=1))   # [6 15] sum across columns
# Think of axis=0 as to obtain row vector and axis=1 to obtain column vector
# PyTorch uses dim instead of axis for similar operations

print(np.mean(a), np.std(a), np.max(a)) 


21
[5 7 9]
[ 6 15]
3.5 1.707825127659933 6


Random Numbers

In [30]:
print(np.random.rand(2, 3))  # Create a 2x3 array with random values
print(np.random.randn(2, 3))  # Create a 2x3 array with random values from a normal distribution
print(np.random.randint(0, 10, (2, 3)))  # Create a 2x3 array with random integers between 0 and 10
print(np.random.choice([1, 2, 3, 4, 5], size=(2, 3)))  # Create a 2x3 array with random choices from the list [1, 2, 3, 4, 5]  
print(np.random.seed(42))  # Set a random seed for reproducibility

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
[[9 5 8]
 [0 9 2]]
[[4 4 1]
 [3 5 3]]
None


Masking and Filtering

In [31]:
x = np.array([1, 2, 3, 4, 5])
print(x[x > 3])  # Select elements greater than 3

a = np.array([[1, 2], [3, 4]])
mask = a > 2
print(mask)        # boolean array
print(a[mask])     # [3 4]

[4 5]
[[False False]
 [ True  True]]
[3 4]


Conversion Between NumPy and PyTorch

In [32]:
import torch

a = np.array([[1, 2], [3, 4]])
t = torch.from_numpy(a)         # NumPy ➝ Torch
a2 = t.numpy()                  # Torch ➝ NumPy

print(t)  # Torch tensor
print(a2)  # NumPy array converted back from Torch tensor


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
[[1 2]
 [3 4]]
