# Exploring Tensors

## Imports

In [41]:
import torch
import numpy as np

## Tensor Initialization  

In [42]:
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Data Tensor: \n{x_data}\n")

# From a NumPy array
np_array = np.array(data) # data to NumPy array first
np_tensor = torch.from_numpy(np_array)
print(f"NumPy Tensor: \n{np_tensor}\n")

# From another tensor
x_ones = torch.ones_like(x_data)  # retains the properties (shape and datatype) of x_data unless specified otherwise
print(f"Ones Tensor: \n{x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)  # specificially overwrites the data type
print(f"Random Tensor: \n{x_rand}\n")

# With random or constant values
# Shape is a tuple of tensor dimensions
shape = (2, 3,)  # 2 rows, 3 columns
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Random Tensor Type: {rand_tensor.dtype}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Ones Tensor Type: {ones_tensor.dtype}\n")
print(f"Zeros Tensor: \n{zeros_tensor}\n")
print(f"Zeros Tensor Type: {zeros_tensor.dtype}\n")



# comma at the end is important for single-element tuples: (2,) is not the same as (2)
x = (3) # <class 'int'>
x = (3,) # <class 'tuple'>



Data Tensor: 
tensor([[1, 2],
        [3, 4]])

NumPy Tensor: 
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.3973, 0.6803],
        [0.3269, 0.3399]])

Random Tensor: 
tensor([[0.3869, 0.0111, 0.0434],
        [0.7623, 0.7386, 0.4639]])

Random Tensor Type: torch.float32

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Ones Tensor Type: torch.float32

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Zeros Tensor Type: torch.float32



## Tensor Attributes  

Shape descriptions, datatype, device stored on

In [43]:
tensor = torch.rand(3, 4)  # 3 rows, 4 columns

print(f"Tensor Shape: {tensor.shape}")  # prints the shape of the tensor
print(f"Tensor Data Type: {tensor.dtype}")  # prints the data type of the tensor
print(f"Tensor Device: {tensor.device}")  # prints the device where the tensor

Tensor Shape: torch.Size([3, 4])
Tensor Data Type: torch.float32
Tensor Device: cpu


## Tensor Operations  

Just some basic ones. There are over 100 available in PyTorch.

In [44]:
# Move tensor to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Tensor moved to Device: {tensor.device}")  # prints the device where the tensor is now stored

# Standard NumPy-like indexing and slicing    
tensor = torch.ones(4, 4)
tensor[:,1] = 0 # for all rows, second column (index 1) make 0
print(tensor)

# Joining tensors (can also use torch.stack)
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim is like axis in NumPy so concat on columns ("extend right")
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0) # dim is like axis in NumPy so concat on rows ("extend down")
print(t2)

# Multiplying tensors
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

# Matrix multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

# In-place operations: Use _ suffix
print(tensor, "\n")
tensor.add_(5) # add 5 to each element in tensor
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3.,

## Bridge with NumPy  

Tensors on CPU and NumPy arrays can share underlying memory locations, and *changing one will change the other*.

In [45]:
# Tensor to NumPy array
t = torch.ones(5)
print(f"torch t: {t}")
n = t.numpy()
print(f"numpy n: {n}")

# A change in the tensor reflects in the NumPy array
# if use without _ suffix for out-of-place, must assign to new tensor: new_t = t.add(1)
t.add_(1) # Torch tensor is an instance of a class, so methods are tied with tensor object
print(f"new t: {t}")
print(f"new n: {n}")

n = np.ones(5)
print(f"numpy n: {n}")
t = torch.from_numpy(n)
print(f"torch t: {t}")
np.add(n, 1, out=n) # NumPy uses a function-oriented approach instead (array, value, out)
print(f"new t: {t}")
print(f"new n: {n}")

torch t: tensor([1., 1., 1., 1., 1.])
numpy n: [1. 1. 1. 1. 1.]
new t: tensor([2., 2., 2., 2., 2.])
new n: [2. 2. 2. 2. 2.]
numpy n: [1. 1. 1. 1. 1.]
torch t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
new t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
new n: [2. 2. 2. 2. 2.]
